remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project. NOTE THE INDENTATION!

title: "Sereknitty"
description: "This app provides knitting patterns and help in a way that is convenient for knitters"
author:
  name: "Danielle Scott"

# Do not change the following line.
  copyright: true
